// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _conv_HH_
#define _conv_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct conv : public sc_module {
    // Port declarations 22
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > A_address0;
    sc_out< sc_logic > A_ce0;
    sc_in< sc_lv<32> > A_q0;
    sc_out< sc_lv<10> > A_address1;
    sc_out< sc_logic > A_ce1;
    sc_in< sc_lv<32> > A_q1;
    sc_out< sc_lv<4> > kernel_address0;
    sc_out< sc_logic > kernel_ce0;
    sc_in< sc_lv<32> > kernel_q0;
    sc_out< sc_lv<4> > kernel_address1;
    sc_out< sc_logic > kernel_ce1;
    sc_in< sc_lv<32> > kernel_q1;
    sc_out< sc_lv<10> > out_r_address0;
    sc_out< sc_logic > out_r_ce0;
    sc_out< sc_logic > out_r_we0;
    sc_out< sc_lv<32> > out_r_d0;


    // Module declarations
    conv(sc_module_name name);
    SC_HAS_PROCESS(conv);

    ~conv();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > reg_258;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<32> > reg_263;
    sc_signal< sc_lv<32> > reg_268;
    sc_signal< sc_lv<32> > reg_273;
    sc_signal< sc_lv<32> > grp_fu_278_p2;
    sc_signal< sc_lv<32> > reg_290;
    sc_signal< sc_lv<32> > grp_fu_284_p2;
    sc_signal< sc_lv<32> > reg_294;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<32> > grp_fu_298_p2;
    sc_signal< sc_lv<32> > reg_304;
    sc_signal< sc_lv<11> > tmp_s_fu_348_p2;
    sc_signal< sc_lv<11> > tmp_s_reg_632;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > exitcond1_fu_308_p2;
    sc_signal< sc_lv<10> > tmp_1_fu_354_p2;
    sc_signal< sc_lv<10> > tmp_1_reg_639;
    sc_signal< sc_lv<11> > tmp_18_fu_384_p2;
    sc_signal< sc_lv<11> > tmp_18_reg_644;
    sc_signal< sc_lv<5> > i_1_fu_390_p2;
    sc_signal< sc_lv<5> > i_1_reg_651;
    sc_signal< sc_lv<11> > tmp_21_fu_420_p2;
    sc_signal< sc_lv<11> > tmp_21_reg_656;
    sc_signal< sc_lv<11> > tmp_6_cast_fu_442_p1;
    sc_signal< sc_lv<11> > tmp_6_cast_reg_666;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond_fu_426_p2;
    sc_signal< sc_lv<10> > tmp_25_fu_456_p2;
    sc_signal< sc_lv<10> > tmp_25_reg_677;
    sc_signal< sc_lv<11> > tmp_8_cast_fu_461_p1;
    sc_signal< sc_lv<11> > tmp_8_cast_reg_682;
    sc_signal< sc_lv<5> > j_1_fu_484_p2;
    sc_signal< sc_lv<5> > j_1_reg_698;
    sc_signal< sc_lv<11> > tmp_cast_fu_490_p1;
    sc_signal< sc_lv<11> > tmp_cast_reg_703;
    sc_signal< sc_lv<11> > tmp_24_fu_504_p2;
    sc_signal< sc_lv<11> > tmp_24_reg_714;
    sc_signal< sc_lv<11> > tmp_28_fu_517_p2;
    sc_signal< sc_lv<11> > tmp_28_reg_724;
    sc_signal< sc_lv<11> > tmp_31_fu_530_p2;
    sc_signal< sc_lv<11> > tmp_31_reg_734;
    sc_signal< sc_lv<32> > tmp1_fu_552_p2;
    sc_signal< sc_lv<32> > tmp1_reg_754;
    sc_signal< sc_lv<32> > tmp_15_reg_759;
    sc_signal< sc_lv<32> > tmp_17_fu_575_p2;
    sc_signal< sc_lv<32> > tmp_17_reg_764;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<5> > i_reg_235;
    sc_signal< sc_lv<5> > j_reg_246;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<64> > tmp_26_cast_fu_451_p1;
    sc_signal< sc_lv<64> > tmp_30_cast_fu_470_p1;
    sc_signal< sc_lv<64> > tmp_27_cast_fu_479_p1;
    sc_signal< sc_lv<64> > tmp_33_cast_fu_499_p1;
    sc_signal< sc_lv<64> > tmp_31_cast_fu_512_p1;
    sc_signal< sc_lv<64> > tmp_34_cast_fu_525_p1;
    sc_signal< sc_lv<64> > tmp_28_cast_fu_534_p1;
    sc_signal< sc_lv<64> > tmp_32_cast_fu_538_p1;
    sc_signal< sc_lv<64> > tmp_35_cast_fu_542_p1;
    sc_signal< sc_lv<64> > tmp_29_cast_fu_580_p1;
    sc_signal< sc_lv<5> > tmp_fu_314_p2;
    sc_signal< sc_lv<10> > tmp_2_fu_324_p3;
    sc_signal< sc_lv<7> > tmp_4_fu_336_p3;
    sc_signal< sc_lv<11> > p_shl4_cast_fu_332_p1;
    sc_signal< sc_lv<11> > p_shl5_cast_fu_344_p1;
    sc_signal< sc_lv<5> > tmp_1_fu_354_p0;
    sc_signal< sc_lv<10> > tmp_6_fu_360_p3;
    sc_signal< sc_lv<7> > tmp_8_fu_372_p3;
    sc_signal< sc_lv<11> > p_shl2_cast_fu_368_p1;
    sc_signal< sc_lv<11> > p_shl3_cast_fu_380_p1;
    sc_signal< sc_lv<10> > tmp_19_fu_396_p3;
    sc_signal< sc_lv<7> > tmp_20_fu_408_p3;
    sc_signal< sc_lv<11> > p_shl_cast_fu_404_p1;
    sc_signal< sc_lv<11> > p_shl1_cast_fu_416_p1;
    sc_signal< sc_lv<5> > tmp_5_fu_432_p2;
    sc_signal< sc_lv<11> > tmp_22_fu_446_p2;
    sc_signal< sc_lv<10> > tmp_6_cast6_fu_438_p1;
    sc_signal< sc_lv<11> > tmp_26_fu_465_p2;
    sc_signal< sc_lv<11> > tmp_23_fu_475_p2;
    sc_signal< sc_lv<11> > tmp_29_fu_494_p2;
    sc_signal< sc_lv<11> > tmp_27_fu_508_p2;
    sc_signal< sc_lv<11> > tmp_30_fu_521_p2;
    sc_signal< sc_lv<32> > tmp3_fu_546_p2;
    sc_signal< sc_lv<32> > tmp7_fu_558_p2;
    sc_signal< sc_lv<32> > tmp6_fu_563_p2;
    sc_signal< sc_lv<32> > tmp4_fu_569_p2;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    sc_signal< sc_lv<10> > tmp_1_fu_354_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_fsm_state1;
    static const sc_lv<11> ap_ST_fsm_state2;
    static const sc_lv<11> ap_ST_fsm_state3;
    static const sc_lv<11> ap_ST_fsm_state4;
    static const sc_lv<11> ap_ST_fsm_state5;
    static const sc_lv<11> ap_ST_fsm_state6;
    static const sc_lv<11> ap_ST_fsm_state7;
    static const sc_lv<11> ap_ST_fsm_state8;
    static const sc_lv<11> ap_ST_fsm_state9;
    static const sc_lv<11> ap_ST_fsm_state10;
    static const sc_lv<11> ap_ST_fsm_state11;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_4;
    static const sc_lv<64> ap_const_lv64_5;
    static const sc_lv<64> ap_const_lv64_6;
    static const sc_lv<64> ap_const_lv64_7;
    static const sc_lv<64> ap_const_lv64_8;
    static const sc_lv<5> ap_const_lv5_1B;
    static const sc_lv<5> ap_const_lv5_1F;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<10> ap_const_lv10_1A;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_A_address0();
    void thread_A_address1();
    void thread_A_ce0();
    void thread_A_ce1();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond1_fu_308_p2();
    void thread_exitcond_fu_426_p2();
    void thread_grp_fu_278_p2();
    void thread_grp_fu_284_p2();
    void thread_grp_fu_298_p2();
    void thread_i_1_fu_390_p2();
    void thread_j_1_fu_484_p2();
    void thread_kernel_address0();
    void thread_kernel_address1();
    void thread_kernel_ce0();
    void thread_kernel_ce1();
    void thread_out_r_address0();
    void thread_out_r_ce0();
    void thread_out_r_d0();
    void thread_out_r_we0();
    void thread_p_shl1_cast_fu_416_p1();
    void thread_p_shl2_cast_fu_368_p1();
    void thread_p_shl3_cast_fu_380_p1();
    void thread_p_shl4_cast_fu_332_p1();
    void thread_p_shl5_cast_fu_344_p1();
    void thread_p_shl_cast_fu_404_p1();
    void thread_tmp1_fu_552_p2();
    void thread_tmp3_fu_546_p2();
    void thread_tmp4_fu_569_p2();
    void thread_tmp6_fu_563_p2();
    void thread_tmp7_fu_558_p2();
    void thread_tmp_17_fu_575_p2();
    void thread_tmp_18_fu_384_p2();
    void thread_tmp_19_fu_396_p3();
    void thread_tmp_1_fu_354_p0();
    void thread_tmp_1_fu_354_p00();
    void thread_tmp_1_fu_354_p2();
    void thread_tmp_20_fu_408_p3();
    void thread_tmp_21_fu_420_p2();
    void thread_tmp_22_fu_446_p2();
    void thread_tmp_23_fu_475_p2();
    void thread_tmp_24_fu_504_p2();
    void thread_tmp_25_fu_456_p2();
    void thread_tmp_26_cast_fu_451_p1();
    void thread_tmp_26_fu_465_p2();
    void thread_tmp_27_cast_fu_479_p1();
    void thread_tmp_27_fu_508_p2();
    void thread_tmp_28_cast_fu_534_p1();
    void thread_tmp_28_fu_517_p2();
    void thread_tmp_29_cast_fu_580_p1();
    void thread_tmp_29_fu_494_p2();
    void thread_tmp_2_fu_324_p3();
    void thread_tmp_30_cast_fu_470_p1();
    void thread_tmp_30_fu_521_p2();
    void thread_tmp_31_cast_fu_512_p1();
    void thread_tmp_31_fu_530_p2();
    void thread_tmp_32_cast_fu_538_p1();
    void thread_tmp_33_cast_fu_499_p1();
    void thread_tmp_34_cast_fu_525_p1();
    void thread_tmp_35_cast_fu_542_p1();
    void thread_tmp_4_fu_336_p3();
    void thread_tmp_5_fu_432_p2();
    void thread_tmp_6_cast6_fu_438_p1();
    void thread_tmp_6_cast_fu_442_p1();
    void thread_tmp_6_fu_360_p3();
    void thread_tmp_8_cast_fu_461_p1();
    void thread_tmp_8_fu_372_p3();
    void thread_tmp_cast_fu_490_p1();
    void thread_tmp_fu_314_p2();
    void thread_tmp_s_fu_348_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
